# Generated by Django 4.2.21 on 2025-06-26 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_type', models.CharField(max_length=255)),
                ('partner_name', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(verbose_name='юридический адресс')),
                ('inn', models.CharField(max_length=12)),
                ('rating', models.PositiveIntegerField(max_length=2, verbose_name='рейтинг')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('article', models.CharField(max_length=10)),
                ('min_price', models.FloatField(verbose_name='минимальная стоимость')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=20)),
                ('date_sale', models.DateField(verbose_name='дата продажи')),
                ('name_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pol.partner', verbose_name='партнер')),
                ('name_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pol.product', verbose_name='продукт')),
            ],
        ),
    ]
